config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'persons/profile'
  get 'main/index'

  get 'persons/profile', as: 'user_root'

  resources :strategies
  resources :games

  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_one :strategy, :foreign_key => 'strategy1_id'
  has_one :strategy, :foreign_key => 'strategy2_id'

  def log_with_linebreaks
    return nil if not game_log

    arr = game_log.split("\n")
    new_arr = []

    arr[0..-2].each do |line|
      new_arr.append(line + ';\\')
    end
    new_arr.append(arr[-1])

    inspect
    new_arr.join
  end
end

app/models/strategy.rb
class Strategy < ApplicationRecord
  belongs_to :user

  def full_title
    user.full_name + ' - ' + title
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Подключаемые модули для авторизации
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  # Связи с другими моделями
  has_many :strategies
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def after_sign_in_path_for(resource)
  #   current_user_path
  # end
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   request.referrer
  # end
end

app/controllers/games_controller.rb
require 'net/http'
require 'json'

class GamesController < ApplicationController
  # Пользователь должен быть аутентифицирован,
  # чтобы выполнять любые действия с играми
  before_action :authenticate_user!

  # Показать все проведенные игры
  def index
    @games = Game.all
  end

  # Создание новой игры из переданных
  # параметрови её запуск
  def create
    # Создание объекта игры из параметров
    @game = current_user.games.create(game_params)

    # Формирование HTTP-запроса к модулю,
    # исполняющему код игры
    uri = URI.parse('http://localhost:4567/play/')
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')

    # Формирование тела запроса
    data = { strategy1: Strategy.find(@game.strategy1_id).code,
             strategy2: Strategy.find(@game.strategy2_id).code }
    request.body = data.to_json

    # Выполнение запроса к модулю и
    # получение результата
    response = http.request(request)
    data = JSON.parse(response.body)

    # Заполнение полей объекта игры
    # значениями полученного результата игры
    @game.success = data['success']
    @game.winner = data['winner']
    @game.game_log = data['game_log']
    @game.game_error = data['game_error']

    # Сохранение игры в базу данных
    @game.save

    # Перенаправление на страницу завершенной игры
    redirect_to @game
  end

  # Запрос на создание новой игры
  def new; end

  # Отображение выбранной игры
  def show
    @game = Game.find(params[:id])
  end

  private

  # Определяет поля объекта "игра"
  def game_params
    params.require(:game).permit(:strategy1_id, :strategy2_id)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
    @strategies = current_user.strategies
    @games = current_user.games
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  # Позволяет пользователю изменить данные своего аккаунта
  # без повторного ввода пароля
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # Определяет параметры, которые пользователь может задать
  # при создании нового аккаунта
  def sign_up_params
    params.require(:user).permit(:full_name, :group, :email, :password, :password_confirmation)
  end

  # Определяет параметры, которые пользователь может задать
  # при изменении своего аккаунта
  def account_update_params
    params.require(:user).permit(:full_name, :group, :email, :password, :password_confirmation)
  end
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  # Пользователь должен быть аутентифицирован,
  # чтобы выполнять любые действия со стратегиями
  before_action :authenticate_user!

  # Отображение всех стратегий
  def index
    @strategies = Strategy.all
  end

  # Создание новой стратегии из
  # переданных параметров
  def create
    # Создание объекта из параметров,
    # переданных из формы
    @strategy = current_user.strategies.create(strategy_params)

    # Сохранение стратегии в базу данных
    @strategy.save

    # Перенаправление пользователя на
    # страницу загруженной стратегии
    redirect_to @strategy
  end

  # Запрос на загрузку новой стратегии
  def new; end

  # Отображение выбранной стратегии
  def show
    @strategy = Strategy.find(params[:id])
  end

  # Запрос на изменение выбранной стратегии
  def edit
    @strategy = Strategy.find(params[:id])
  end

  # Обновление выбранной стратегии по
  # переданным параметрам
  def update
    @strategy = Strategy.find(params[:id])

    # Если стратегия была успешно изменена,
    # перенаправить пользователя на её страницу
    if @strategy.update(strategy_params)
      redirect_to @strategy
    end
  end

  # Удаление выбранной стратегии
  def destroy
    @strategy = Strategy.find(params[:id])

    # Удалить стратегию, если пользователь является
    # её автором либо администратором
    if @strategy.user == current_user or current_user.admin?
      @strategy.destroy
      redirect_to strategies_path
    end
  end

  private

  # Определяет поля объекта "стратегия"
  def strategy_params
    params.require(:strategy).permit(:title, :code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/strategies_helper.rb
module StrategiesHelper
end

app/views/games/index.html.erb
<%= link_to 'На главную', main_index_path %>

<h1>История игр</h1>

<table>
  <tr>
    <td><strong>Время</strong></td>
    <td><strong>Создал</strong></td>
    <td><strong>Стратегия пользователя</strong></td>
    <td><strong>Стратегия противника</strong></td>
    <td><strong>Результат</strong></td>
  </tr>
  <% @games.each do |game| %>
    <tr>
      <td><%= game.created_at.strftime("%Y.%m.%d %H:%M") %></td>
      <td><%= game.user.full_name %></td>
      <td><%= Strategy.find(game.strategy1_id).full_title %></td>
      <td><%= Strategy.find(game.strategy2_id).full_title %></td>
      <td><%= game.success ? game.winner : 'Ошибка' %></td>
      <td><%= link_to 'Показать', game_path(game) %></td>
    </tr>
  <% end %>
</table>

app/views/games/new.html.erb
<h1>Создать игру</h1>

<%= form_with scope: :game, url: :games, local: true do |form| %>
  <table>
    <% if current_user.admin? %>
      <tr>
        <td><%= form.label 'Ваша стратегия' %></td>
        <td><%= collection_select(:game, :strategy1_id,
                                  Strategy.all, :id, :full_title) %></td>
      </tr>
    <% else %>
      <tr>
        <td><%= form.label 'Ваша стратегия' %></td>
        <td><%= collection_select(:game, :strategy1_id,
                                  current_user.strategies, :id, :title) %></td>
      </tr>
    <% end %>
    <tr>
      <td><%= form.label 'Стратегия противника' %></td>
      <td><%= collection_select(:game, :strategy2_id,
                                Strategy.all, :id, :full_title) %></td>
    </tr>
  </table>

  <%= form.submit 'Создать игру' %>
<% end %>

<%= link_to 'Вернуться', :back %>

app/views/games/show.html.erb
<%= link_to 'Вернуться', :back %>

<% if @game.success %>
  <h1>Game replay:</h1>

<!-- Элемент страницы, отвечающий за игровое поле в целом -->
  <div class="board">
    <!-- Игровое поле первого игрока -->
    <div class="field" id="P1">
      <!-- Вложенный цикл, отображающий поле 10х10 элементов -->
      <% 10.times do |y| %>
        <div class="field-row">
          <% 10.times do |x| %>
            <button class="square" id="<%= "P1_#{x}_#{y}" %>"/>
          <% end %>
        </div>
      <% end %>
    </div>

    <!-- Игровое поле второго игрока -->
    <div class="field" id="P2">
      <!-- Вложенный цикл, отображающий поле 10х10 элементов -->
      <% 10.times do |y| %>
        <div class="field-row">
          <% 10.times do |x| %>
            <button class="square" id="<%= "P2_#{x}_#{y}" %>"/>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <p><strong>Winner:</strong> <%= @game.winner %></p>
  <p><strong>Game log:</strong></p>
  <pre><code><%= @game.game_log %></code></pre>

<% else %>
  <h1>Game status:</h1>

  <p><strong>Error:</strong></p>
  <pre><code><%= @game.game_error %></code></pre>
<% end %>

<%= javascript_tag "play(\"#{@game.log_with_linebreaks}\")" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Front</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!--Отображение нотификаций при авторизации пользователя-->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>Морской бой</h1>

<% if user_signed_in? %>
  <span>Здравствуйте, <%= current_user.full_name %>
    (<%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>)</span>
  <ul>
    <li><%= link_to 'Перейти в профиль', persons_profile_path %></li>
    <li><%= link_to 'Посмотреть все стратегии', strategies_path %></li>
    <li><%= link_to 'Посмотреть общую историю игр', games_path %></li>
    <li><%= link_to 'Создать игру', new_game_path %></li>
  </ul>
<% else %>
  <%= link_to 'Войти', new_user_session_path %>
  или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

app/views/persons/profile.html.erb
<%= link_to 'На главную', main_index_path %>

<h1>Профиль</h1>
<p><%= 'Администратор' if current_user.admin? %></p>

<h2>Данные:</h2>
<p>Имя: <%= current_user.full_name %></p>
<p>Группа: <%= current_user.group %></p>
<p>Email: <%= current_user.email %></p>
<%= link_to 'Изменить', edit_user_registration_path %>

<h2>Список загруженных стратегий:</h2>
<p><%= link_to 'Загрузить новую стратегию', new_strategy_path %></p>

<% if @strategies %>
  <table>
    <% @strategies.each do |strategy| %>
    <tr>
      <td><%= strategy.title %></td>
      <td><%= link_to 'Показать', strategies_path(strategy) %></td>
      <td><%= link_to 'Удалить', [strategy],
                      method: :delete,
                      data: { confirm: 'Вы уверены, что хотите удалить стратегию?' } %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p>Пока не загружено ни одной стратегии</p>
<% end %>

<h2>Список проведенных игр:</h2>
<% if @games %>
  <table>
    <tr>
      <td><strong>Время</strong></td>
      <td><strong>Стратегия пользователя</strong></td>
      <td><strong>Стратегия противника</strong></td>
      <td><strong>Результат</strong></td>
    </tr>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.created_at.strftime("%Y.%m.%d %H:%M") %></td>
        <td><%= Strategy.find(game.strategy1_id).title %></td>
        <td><%= Strategy.find(game.strategy2_id).full_title %></td>
        <td><%= game.success ? game.winner : 'Ошибка' %></td>
        <td><%= link_to 'Показать', game_path(game) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Пока не загружено ни одной стратегии</p>
<% end %>

app/views/strategies/edit.html.erb
<h1>Изменить стратегию</h1>

<%= form_with scope: :strategy, url: :strategies, local: true do |form| %>
  <p>
    <%= form.label 'Название' %><br>
    <%= form.text_field 'title', autocomplete: 'title' %>
  </p>

  <p>
    <%= form.label 'Код стратегии' %><br>
    <%= form.text_area 'code', autocomplete: 'code' %>
  </p>

  <p>
    <%= form.submit 'Обновить'%>
  </p>
<% end %>

<%= link_to 'Вернуться', :back %>

app/views/strategies/index.html.erb
<%= link_to 'На главную', main_index_path %>

<h1>Список всех стратегий:</h1>

<table>
  <tr>
    <td><strong>Название</strong></td>
    <td><strong>Автор</strong></td>
  </tr>
  <% @strategies.each do |strategy| %>
    <tr>
      <td><%= strategy.title %></td>
      <td><%= strategy.user.full_name %></td>
      <% if strategy.user == current_user or current_user.admin? %>
        <td><%= link_to 'Показать', strategy_path(strategy) %></td>
        <td><%= link_to 'Удалить', [strategy],
                         method: :delete,
                         data: { confirm: 'Вы уверены, что хотите удалить стратегию?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/strategies/new.html.erb
<h1>Загрузить новую стратегию</h1>

<%= form_with scope: :strategy, url: :strategies, local: true do |form| %>
  <p>
    <%= form.label 'Название' %><br>
    <%= form.text_field 'title' %>
  </p>

  <p>
    <%= form.label 'Код стратегии' %><br>
    <%= form.text_area 'code' %>
  </p>

  <p>
    <%= form.submit 'Загрузить'%>
  </p>
<% end %>

<%= link_to 'Вернуться', :back %>

app/views/strategies/show.html.erb
<%= link_to 'Вернуться', :back %>
<p>
  <strong>Автор:</strong>
  <%= @strategy.user ? @strategy.user.full_name : 'Не указан' %>
</p>

<p>
  <strong>Название стратегии:</strong>
  <%= @strategy.title %>
</p>

<p>
  <strong>Код стратегии:</strong>
</p>
<pre><code><%= @strategy.code %></code></pre>